"""мелкие правки

Revision ID: 00c8dfb56c4b
Revises: fee48e0a6baf
Create Date: 2021-04-19 15:39:07.097709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c8dfb56c4b'
down_revision = 'fee48e0a6baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
