"""удаление категорий

Revision ID: 777b5b6fa3ae
Revises: 00c8dfb56c4b
Create Date: 2021-04-24 15:39:08.017003

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '777b5b6fa3ae'
down_revision = '00c8dfb56c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards', saColumn('description', sa.String(), default="", nullable=False))
    op.alter_column('awards', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                    default="Достижение")
    op.add_column('news', sa.Column('paths_to_images', sa.String(), default="", nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'paths_to_images')
    op.alter_column('awards', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('awards', 'description')
    op.drop_column('awards', 'creation_date')
    # ### end Alembic commands ###
