"""Изменение дат

Revision ID: ed8578a2d812
Revises: ff7c5f918dfd
Create Date: 2021-04-25 17:18:25.725445

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed8578a2d812'
down_revision = 'ff7c5f918dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    '''
    with op.batch_alter_table('awards') as bop:
        bop.alter_column('creation_time', new_column_name='creation_date')
    op.alter_column('awards', 'direction',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('news', 'content',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('news', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('news', 'creation_time')
    '''
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('creation_time', sa.DATETIME(), nullable=True))
    op.alter_column('news', 'title',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('news', 'content',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('news', 'creation_date')
    op.alter_column('awards', 'direction',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_column('awards', 'modified_date')
    # ### end Alembic commands ###
